### ISSUE TITLE
consider tidying up use of css

### ISSUE THREAD

**Issue by danmarsden** [MMBR-IO/moodle-enrol_mmbrio#25]
normally plugins will use a styles.css file in the root of the plugin to contain all the css for the plugin - this is because moodle combines all these css files into a single file and caches it nicely for speed.

You might want to look at doing this, but you will need to update your css to be more specific - you have classes in your css like ".error" ".success" - these class names could be used in other pages within Moodle and you only want your css to apply to the mmbrio pages.
Moodle provides a number of automatically added css classes to the body tag that relate to the page being loaded that might be useful - but standalone files like .mmbrio/enrol.php will have a css tag like "path-enrol-mmbrio" automatically added to the page body to make it easy to target.

**Comment by BarmaleyHD** [comment]
Thank you for for your comment. 
I've update and cleaned up styling files as well as replaced some custom css with bootstrap classes.
